/* 
 * Copyright (C) 2017 ESDC/ESA 2017
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package esavo.vospec.util;

import esavo.vospec.main.VOSpecDetached;
import java.awt.*;

/**
 *
 * @author  ibarbarisi
 */
public class ChooserSave extends javax.swing.JDialog {
    
    public VOSpecDetached aioSpecToolDetached;
    
    /** Creates new form ChooserSave */
    public ChooserSave(java.awt.Frame parent, boolean modal) {
        super(parent, modal);       
    }
    
    public ChooserSave() {
        initComponents();
        getChoice();
        this.setTitle("Save as");
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width / 2 - this.getWidth() /2, (screenSize.height / 2)- this.getHeight() /2);

    } 
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        image = new javax.swing.JRadioButton();
        votable = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Save as:");
        jPanel1.add(jLabel1);

        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 2));
        jPanel1.add(jSeparator1);

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setText("Image");
        jPanel1.add(image);

        votable.setBackground(new java.awt.Color(255, 255, 255));
        votable.setText("SDM 1.03 VOTable");
        jPanel1.add(votable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setBackground(new java.awt.Color(231, 230, 230));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try { 
            if (!(image.getSelectedObjects() == null)){
                System.out.println("im "); 
                aioSpecToolDetached.savingAsImage();
            }
            if (!(votable.getSelectedObjects() == null)) {
                System.out.println("vo ");
                aioSpecToolDetached.savingAsVOTable();
            }
            
            this.dispose();
        } catch (java.lang.Exception e) {
                e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
  
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ChooserSave(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grp;
    private javax.swing.JRadioButton image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton votable;
    // End of variables declaration//GEN-END:variables
    
    
    public void getChoice() {
        
        grp.add(image);
        grp.add(votable);
        
        image.setMnemonic('I');
        votable.setMnemonic('V');
        
        image.setSelected(true);
            
    }
    
    public void setAioSpecToolDetached(VOSpecDetached aioSpecToolDetached) {
        this.aioSpecToolDetached = aioSpecToolDetached;
    } 
}
