/* 
 * Copyright (C) 2017 ESDC/ESA 2017
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package esavo.vospec.plot;

import esavo.vospec.main.*;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author  ibarbarisi
 */
public class PlotSettings extends javax.swing.JDialog {
    
    
    public VOSpecDetached aioSpecToolDetached;
    public ExtendedPlot plot;
    public Color bg;
    public Color fg;
        
    public PlotSettings() { 
        initComponents();
        //this.setSize(450,300);
    }
    
    public PlotSettings(ExtendedPlot plot) { 
        this();
        this.plot = plot;  
        bgColor.setBackground(plot.getBackground());
        fgColor.setBackground(plot.getForeground());
        titleText.setText(plot.getTitle());
        xAxisText.setText(plot.getXLabel());
        yAxisText.setText(plot.getYLabel());

        waveMinText.setText(String.valueOf(plot.getXMin()));
        waveMaxText.setText(String.valueOf(plot.getXMax()));
        fluxMinText.setText(String.valueOf(plot.getYMin()));
        fluxMaxText.setText(String.valueOf(plot.getYMax()));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width / 2 - this.getWidth() /2, (screenSize.height / 2)- this.getHeight() /2);

    }
    
    public void setAioSpecToolDetached(VOSpecDetached aioSpecToolDetached) {
        this.aioSpecToolDetached = aioSpecToolDetached;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JTextField();
        AxisPanel = new javax.swing.JPanel();
        xAxisLabel = new javax.swing.JLabel();
        xAxisText = new javax.swing.JTextField();
        yAxisLabel = new javax.swing.JLabel();
        yAxisText = new javax.swing.JTextField();
        ColorPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();
        backgroundText = new javax.swing.JTextField();
        bgColor = new javax.swing.JButton();
        foregroundLabel = new javax.swing.JLabel();
        foregroundText = new javax.swing.JTextField();
        fgColor = new javax.swing.JButton();
        BindingsPanel = new javax.swing.JPanel();
        waveMaxLabel = new javax.swing.JLabel();
        waveMaxText = new javax.swing.JTextField();
        fluxMaxLabel = new javax.swing.JLabel();
        fluxMaxText = new javax.swing.JTextField();
        waveMinLabel = new javax.swing.JLabel();
        waveMinText = new javax.swing.JTextField();
        fluxMinLabel = new javax.swing.JLabel();
        fluxMinText = new javax.swing.JTextField();
        selectPanel = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(222, 220, 220));
        titlePanel.setPreferredSize(new java.awt.Dimension(510, 20));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Plot Settings ");
        titlePanel.add(jLabel1);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        settingPanel.setBackground(new java.awt.Color(244, 241, 239));
        settingPanel.setPreferredSize(new java.awt.Dimension(410, 340));
        settingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        TitlePanel.setBackground(new java.awt.Color(244, 241, 239));
        TitlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N
        TitlePanel.setPreferredSize(new java.awt.Dimension(400, 70));
        TitlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 10));

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setText("Title Text");
        titleLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        TitlePanel.add(titleLabel);

        titleText.setFont(new java.awt.Font("Dialog", 0, 10));
        titleText.setForeground(new java.awt.Color(102, 102, 102));
        titleText.setPreferredSize(new java.awt.Dimension(80, 17));
        TitlePanel.add(titleText);

        settingPanel.add(TitlePanel);

        AxisPanel.setBackground(new java.awt.Color(244, 241, 239));
        AxisPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Axis Labels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N
        AxisPanel.setPreferredSize(new java.awt.Dimension(400, 70));
        AxisPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 10));

        xAxisLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        xAxisLabel.setForeground(new java.awt.Color(102, 102, 102));
        xAxisLabel.setText("X Axis");
        xAxisLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        AxisPanel.add(xAxisLabel);

        xAxisText.setFont(new java.awt.Font("Dialog", 0, 10));
        xAxisText.setForeground(new java.awt.Color(102, 102, 102));
        xAxisText.setPreferredSize(new java.awt.Dimension(120, 17));
        AxisPanel.add(xAxisText);

        yAxisLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        yAxisLabel.setForeground(new java.awt.Color(102, 102, 102));
        yAxisLabel.setText("        Y Axis ");
        yAxisLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        AxisPanel.add(yAxisLabel);

        yAxisText.setFont(new java.awt.Font("Dialog", 0, 10));
        yAxisText.setForeground(new java.awt.Color(102, 102, 102));
        yAxisText.setPreferredSize(new java.awt.Dimension(120, 17));
        AxisPanel.add(yAxisText);

        settingPanel.add(AxisPanel);
        AxisPanel.getAccessibleContext().setAccessibleName("Axis");

        ColorPanel.setBackground(new java.awt.Color(244, 241, 239));
        ColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N
        ColorPanel.setPreferredSize(new java.awt.Dimension(400, 70));
        ColorPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 10));

        backgroundLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        backgroundLabel.setForeground(new java.awt.Color(102, 102, 102));
        backgroundLabel.setText("Background");
        backgroundLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        ColorPanel.add(backgroundLabel);

        backgroundText.setEditable(false);
        backgroundText.setFont(new java.awt.Font("Dialog", 0, 10));
        backgroundText.setForeground(new java.awt.Color(102, 102, 102));
        backgroundText.setPreferredSize(new java.awt.Dimension(80, 17));
        ColorPanel.add(backgroundText);

        bgColor.setToolTipText("Choose Color");
        bgColor.setMaximumSize(new java.awt.Dimension(10, 10));
        bgColor.setMinimumSize(new java.awt.Dimension(10, 10));
        bgColor.setPreferredSize(new java.awt.Dimension(15, 15));
        bgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorActionPerformed(evt);
            }
        });
        ColorPanel.add(bgColor);

        foregroundLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        foregroundLabel.setForeground(new java.awt.Color(102, 102, 102));
        foregroundLabel.setText("            Foreground");
        foregroundLabel.setPreferredSize(new java.awt.Dimension(110, 13));
        ColorPanel.add(foregroundLabel);

        foregroundText.setEditable(false);
        foregroundText.setFont(new java.awt.Font("Dialog", 0, 10));
        foregroundText.setForeground(new java.awt.Color(102, 102, 102));
        foregroundText.setPreferredSize(new java.awt.Dimension(80, 17));
        ColorPanel.add(foregroundText);

        fgColor.setBackground(new java.awt.Color(0, 0, 0));
        fgColor.setToolTipText("ChooseColor");
        fgColor.setMaximumSize(new java.awt.Dimension(10, 10));
        fgColor.setMinimumSize(new java.awt.Dimension(10, 10));
        fgColor.setPreferredSize(new java.awt.Dimension(15, 15));
        fgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgColorActionPerformed(evt);
            }
        });
        ColorPanel.add(fgColor);

        settingPanel.add(ColorPanel);

        BindingsPanel.setBackground(new java.awt.Color(244, 241, 239));
        BindingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bindings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N
        BindingsPanel.setPreferredSize(new java.awt.Dimension(400, 90));
        BindingsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 10));

        waveMaxLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        waveMaxLabel.setForeground(new java.awt.Color(102, 102, 102));
        waveMaxLabel.setText("Wave max");
        waveMaxLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        BindingsPanel.add(waveMaxLabel);

        waveMaxText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        waveMaxText.setForeground(new java.awt.Color(102, 102, 102));
        waveMaxText.setPreferredSize(new java.awt.Dimension(80, 17));
        BindingsPanel.add(waveMaxText);

        fluxMaxLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        fluxMaxLabel.setForeground(new java.awt.Color(102, 102, 102));
        fluxMaxLabel.setText("             Flux max");
        fluxMaxLabel.setPreferredSize(new java.awt.Dimension(110, 13));
        BindingsPanel.add(fluxMaxLabel);

        fluxMaxText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fluxMaxText.setForeground(new java.awt.Color(102, 102, 102));
        fluxMaxText.setPreferredSize(new java.awt.Dimension(80, 17));
        BindingsPanel.add(fluxMaxText);

        waveMinLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        waveMinLabel.setForeground(new java.awt.Color(102, 102, 102));
        waveMinLabel.setText("Wave min");
        waveMinLabel.setPreferredSize(new java.awt.Dimension(70, 13));
        BindingsPanel.add(waveMinLabel);

        waveMinText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        waveMinText.setForeground(new java.awt.Color(102, 102, 102));
        waveMinText.setPreferredSize(new java.awt.Dimension(80, 17));
        BindingsPanel.add(waveMinText);

        fluxMinLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        fluxMinLabel.setForeground(new java.awt.Color(102, 102, 102));
        fluxMinLabel.setText("             Flux min");
        fluxMinLabel.setPreferredSize(new java.awt.Dimension(110, 13));
        BindingsPanel.add(fluxMinLabel);

        fluxMinText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fluxMinText.setForeground(new java.awt.Color(102, 102, 102));
        fluxMinText.setPreferredSize(new java.awt.Dimension(80, 17));
        BindingsPanel.add(fluxMinText);

        settingPanel.add(BindingsPanel);

        selectPanel.setBackground(new java.awt.Color(244, 241, 239));
        selectPanel.setPreferredSize(new java.awt.Dimension(400, 33));
        selectPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        selectButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        selectButton.setForeground(new java.awt.Color(51, 51, 51));
        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        selectPanel.add(selectButton);

        settingPanel.add(selectPanel);

        getContentPane().add(settingPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgColorActionPerformed
        
        Color initialBackground = plot.getForeground();
        
        fg = JColorChooser.showDialog(null, "Change Background", initialBackground);
        if (fg != null) {
          foregroundText.setText(fg.toString());
        }
        fgColor.setBackground(fg);
        
    }//GEN-LAST:event_fgColorActionPerformed

    private void bgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorActionPerformed
        
        Color initialBackground = plot.getBackground();
        bg = JColorChooser.showDialog(null, "Change Background", initialBackground);
        if (bg != null) {
          backgroundText.setText(bg.toString());
        }
        bgColor.setBackground(bg);
                
    }//GEN-LAST:event_bgColorActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        
        String title = titleText.getText();
        if (title.equals("")){
           title = plot.getTitle();
        }
        //String fontTitle = titleFontLabel.getText();
        
        String xAxis = xAxisText.getText();
        if (xAxis.equals("")){
            xAxis = plot.getXLabel();       
        }
        
        String yAxis = yAxisText.getText();
        if (yAxis.equals("")){
            yAxis = plot.getYLabel();       
        }
        
        //if (backgroundText.equals("")){
           //bgColor.setBackground(new Color(235,235,235));      
           //bgColor.setBackground(bgColor.getBackground());
            System.out.println("Empty backGround Text");
           plot.setBackground(bgColor.getBackground());
           bg = bgColor.getBackground();
        //}
        
        //if (foregroundText.equals("Empty foreGround Text")){
           //fgColor.setBackground(new Color(102,102,102)); 
           plot.setBackground(fgColor.getBackground());
           fg = fgColor.getBackground();
        //}
        //String axisFont = labelText.getText();
        
           Double waveMin = plot.getXMin();
           Double waveMax = plot.getXMax();
           Double fluxMin = plot.getYMin();
           Double fluxMax = plot.getYMax();

           try{
               waveMin = Double.valueOf(waveMinText.getText());
           }catch(Exception e){
               e.printStackTrace();
           }
           
           try{
               waveMax = Double.valueOf(waveMaxText.getText());
           }catch(Exception e){
               e.printStackTrace();
           }
           
           try{
               fluxMin = Double.valueOf(fluxMinText.getText());
           }catch(Exception e){
               e.printStackTrace();
           }
           
           try{
               fluxMax = Double.valueOf(fluxMaxText.getText());
           }catch(Exception e){
               e.printStackTrace();
           }
           

           plot.goTo(waveMin, fluxMin, waveMax, fluxMax);

           plot.repaint();


        //aioSpecToolDetached.sv = new SpectraViewer(plot,bg,fg,title,fontTitle,xAxis,yAxis,axisFont);
        aioSpecToolDetached.sv = new SpectraViewer(plot,bg,fg,title,xAxis,yAxis);
        aioSpecToolDetached.sv.setBackgroundAndForeground(bg, fg);
        aioSpecToolDetached.repaint();
        this.dispose();
        
    }//GEN-LAST:event_selectButtonActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AxisPanel;
    private javax.swing.JPanel BindingsPanel;
    private javax.swing.JPanel ColorPanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel backgroundLabel;
    public javax.swing.JTextField backgroundText;
    public javax.swing.JButton bgColor;
    public javax.swing.JButton fgColor;
    private javax.swing.JLabel fluxMaxLabel;
    public javax.swing.JTextField fluxMaxText;
    private javax.swing.JLabel fluxMinLabel;
    public javax.swing.JTextField fluxMinText;
    private javax.swing.JLabel foregroundLabel;
    public javax.swing.JTextField foregroundText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField titleText;
    private javax.swing.JLabel waveMaxLabel;
    public javax.swing.JTextField waveMaxText;
    private javax.swing.JLabel waveMinLabel;
    public javax.swing.JTextField waveMinText;
    private javax.swing.JLabel xAxisLabel;
    private javax.swing.JTextField xAxisText;
    private javax.swing.JLabel yAxisLabel;
    private javax.swing.JTextField yAxisText;
    // End of variables declaration//GEN-END:variables

}


