PACKAGE     = esavo.fit

SOURCE      = \
    FitUtils.java \
    Fit.java \
    TsapBestFit.java \
    Spline.java \
    TsapCallRead.java \
    LevenbergMarquardt.java \
    OrderedSpectrum.java \
    ChiSquareFitting.java \
    TSAPmodel.java \
    SED.java \
    SamplingData.java \
    TSAPmodelUtils.java \
        
     
    
              
       
RMI_SOURCE  =

MAIN        =

include $(JAVA_DEV_ROOT)/Makefile

