PACKAGE     = esavo.utils.units.dimeq

SOURCE      = \
    Constant.java \
    GeneralConverter.java \
    SpectrumConverter.java \
    Quantity.java \
    Variable.java \
    Constant.java \
    Unit.java \
       


RMI_SOURCE  =

MAIN        =

include $(JAVA_DEV_ROOT)/Makefile

