/* 
 * Copyright (C) 2017 ESDC/ESA 2017
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package esavo.vospec.main;


import esavo.vospec.util.*;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author  ibarbarisi
 */
public class About extends javax.swing.JDialog {
    
    public String about;
    public VOSpecDetached aioSpecToolDetached;
    
    /** Creates new form AioSpecInfo */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }
    
     public About(VOSpecDetached aioSpecToolDetached) {
        this.setSize(310,350);
        this.aioSpecToolDetached = aioSpecToolDetached;
        initComponents();
        this.setTitle("VOSpec About");
        jLabel2.setText("V. " + EnvironmentDefs.getVERSION());

        this.setResizable(false);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width / 2 - this.getWidth() /2, (screenSize.height / 2)- this.getHeight() /2);
               
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        aboutDataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aboutContainerPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exitButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        aboutDataPanel.setBackground(new java.awt.Color(240, 236, 236));
        aboutDataPanel.setPreferredSize(new java.awt.Dimension(400, 240));
        aboutDataPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esavo/vospec/images/logoAbout.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(390, 50));
        aboutDataPanel.add(jLabel1);

        aboutContainerPanel.setBackground(new java.awt.Color(240, 236, 236));
        aboutContainerPanel.setPreferredSize(new java.awt.Dimension(390, 140));
        aboutContainerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jSeparator1.setPreferredSize(new java.awt.Dimension(380, 2));
        aboutContainerPanel.add(jSeparator1);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("ESA - Science Operation Department    ");
        aboutContainerPanel.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("European Space Astronomy Centre        ");
        jLabel7.setPreferredSize(new java.awt.Dimension(245, 13));
        aboutContainerPanel.add(jLabel7);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ESAC, ESA VO Team");
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 13));
        aboutContainerPanel.add(jLabel3);
        jLabel3.getAccessibleContext().setAccessibleName("ESAC, ESAVO Team");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Villanueva de la Cañada");
        jLabel5.setPreferredSize(new java.awt.Dimension(350, 13));
        aboutContainerPanel.add(jLabel5);

        jLabel8.setFont(new java.awt.Font("Luxi Sans", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("http://esavo.esa.int/");
        aboutContainerPanel.add(jLabel8);

        aboutDataPanel.add(aboutContainerPanel);

        exitButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        exitButton.setForeground(new java.awt.Color(112, 111, 111));
        exitButton.setText("Close");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        aboutDataPanel.add(exitButton);

        jPanel1.setBackground(new java.awt.Color(240, 236, 236));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 3));

        jLabel2.setBackground(new java.awt.Color(240, 236, 236));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("V. 3.1");
        jPanel1.add(jLabel2);

        aboutDataPanel.add(jPanel1);

        getContentPane().add(aboutDataPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new About(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutContainerPanel;
    private javax.swing.JPanel aboutDataPanel;
    private javax.swing.JToggleButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
   


}
