/* 
 * Copyright (C) 2017 ESDC/ESA 2017
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package esavo.vospec.main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.*;

/**
 *
 * @author  jgonzale
 */
public class QueryInfo extends javax.swing.JDialog{
    

    public QueryInfo(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width / 2 - this.getWidth() /2, (screenSize.height / 2)- this.getHeight() /2);
    }

    public QueryInfo(Vector<String> successResults, Vector<String> failResults) {

        initComponents();
        setSize(370,385);
 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width / 2 - this.getWidth() /2, (screenSize.height / 2)- this.getHeight() /2);

        for(int i=0;i<successResults.size();i++){
            jTextArea1.append(successResults.get(i));
            jTextArea1.append(System.getProperty("line.separator"));            
        }

        for(int i=0;i<failResults.size();i++){
            jTextArea1.append(failResults.get(i));
            jTextArea1.append(System.getProperty("line.separator"));
        }

        this.jTextArea1.repaint();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metaDataPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Query results");
        setAlwaysOnTop(true);

        metaDataPanel.setBackground(new java.awt.Color(240, 236, 236));
        metaDataPanel.setPreferredSize(new java.awt.Dimension(310, 340));
        metaDataPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 236, 236));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 40));

        saveButton.setText("OK");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(116, 116, 116)
                .add(saveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(saveButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        metaDataPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Query results:");
        jPanel2.add(jLabel1);

        metaDataPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        metaDataPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(metaDataPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        this.dispose();

                          
    }//GEN-LAST:event_saveButtonActionPerformed
    
    public void dispose() {
        super.dispose();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new QueryInfo(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel metaDataPanel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    
}
