/* 
 * Copyright (C) 2017 ESDC/ESA 2017
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package esavo.vospec.main;


/**
 *
 * @author  ibarbarisi
 */
public class VOSpecFullSize extends javax.swing.JDialog {
    
    
    /** Creates new form AioSpecInfo */
    public VOSpecFullSize(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }
    
     public VOSpecFullSize() {
        initComponents();
        this.setSize(450,300);
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        displayPane = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        displayPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(displayPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel displayPane;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
   


}
